import Product from "../modules/product/product.model.js";
import sequelize from "../config/database.js";

const products = [
  {
    name: "Summer Floral Dress",
    brand: "FOREVER 21",
    price: 1899,
    originalPrice: 3499,
    discount: 46,
    rating: 4.4,
    reviews: 287,
    image: "arito1.jpg",
    category: "women-fashion",
    description:
      "Beautiful summer floral dress perfect for any occasion. Light and breathable fabric.",
  },
  {
    name: "Black Sneakers",
    brand: "NIKE",
    price: 4999,
    originalPrice: 7499,
    discount: 33,
    rating: 4.7,
    reviews: 891,
    image: "arito2.jpg",
    category: "men-footwear",
    description:
      "Comfortable black sneakers with modern design. Perfect for casual and sports wear.",
  },
  {
    id: 5,
    name: "Striped Polo Shirt",
    brand: "TOMMY HILFIGER",
    price: 2199,
    originalPrice: 4399,
    discount: 50,
    rating: 4.5,
    reviews: 445,
    image: "arito3.jpg",
    category: "shirts",
    description: "Classic striped polo shirt in premium quality. Great for both casual and formal wear.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"]
  },
  {
    id: 7,
    name: "Casual Chinos",
    brand: "PETER ENGLAND",
    price: 1799,
    originalPrice: 3599,
    discount: 50,
    rating: 4.4,
    reviews: 378,
    image: "arito4.jpg",
    category: "formals",
    description: "Smart casual chinos perfect for everyday wear. Comfortable and stylish.",
    sizes: ["28", "30", "32", "34", "36"]
  },
  {
    id: 8,
    name: "Sports Backpack",
    brand: "DECATHLON",
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    rating: 4.6,
    reviews: 534,
    image: "baby1.jpg",
    category: "Accessories",
    description: "Durable sports backpack with multiple compartments. Perfect for gym and travel.",
    sizes: ["One Size"]
  },
  {
    id: 9,
    name: "Beauty Essentials Kit",
    brand: "MAC",
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.7,
    reviews: 456,
    image: "baby2.jpg",
    category: "beauty-makeup",
    description: "Complete beauty essentials kit with premium quality products.",
    sizes: ["One Size"]
  },
  {
    id: 10,
    name: "Kids Adventure Jacket",
    brand: "MOTHERCARE",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.5,
    reviews: 267,
    image: "baby3.jpg",
    category: "kids-clothing",
    description: "Colorful and comfortable jacket for kids. Perfect for outdoor adventures.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 61,
    name: "Kids Sport Sneakers",
    brand: "PUMA",
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    rating: 4.4,
    reviews: 210,
    image: "baby4.jpg",
    category: "kids-footwear",
    description: "Comfortable sneakers for kids to run and play.",
    sizes: ["10", "11", "12", "13"]
  },
  {
    id: 62,
    name: "Kids Cartoon Hoodie",
    brand: "MINISO",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.2,
    reviews: 145,
    image: "bg.jpg",
    category: "kids-clothing",
    description: "Warm cartoon hoodie for playful kids.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 63,
    name: "Kids Party Dress",
    brand: "BABY HUG",
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.6,
    reviews: 182,
    image: "bshoe1.jpg",
    category: "kids-outfits",
    description: "Cute party dress for special celebrations.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 64,
    name: "Kids Fun Backpack",
    brand: "DECATHLON",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.3,
    reviews: 120,
    image: "bshoe2.jpg",
    category: "kids-accessories",
    description: "Durable backpack perfect for school and trips.",
    sizes: ["One Size"]
  },
  {
    id: 65,
    name: "Kids Soccer Tee",
    brand: "ADIDAS",
    price: 1099,
    originalPrice: 2199,
    discount: 50,
    rating: 4.4,
    reviews: 154,
    image: "bshoe3.jpg",
    category: "kids-sports",
    description: "Breathable sports tee for active kids.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 66,
    name: "Kids Toy Set",
    brand: "TOY STORY",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.5,
    reviews: 93,
    image: "bshoe4.jpg",
    category: "kids-toys",
    description: "Fun playset to keep kids entertained for hours.",
    sizes: ["One Size"]
  },
  {
    id: 67,
    name: "Glow Serum",
    brand: "Olay",
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    rating: 4.6,
    reviews: 275,
    image: "chudi1.jpg",
    category: "beauty-skincare",
    description: "Hydrating glow serum for radiant skin.",
    sizes: ["One Size"]
  },
  {
    id: 68,
    name: "Perfume Mist",
    brand: "Dior",
    price: 3799,
    originalPrice: 7599,
    discount: 50,
    rating: 4.7,
    reviews: 215,
    image: "chudi2.jpg",
    category: "beauty-fragrance",
    description: "Light and elegant fragrance mist for everyday use.",
    sizes: ["One Size"]
  },
  {
    id: 69,
    name: "Makeup Brush Set",
    brand: "Sephora",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.5,
    reviews: 198,
    image: "chudi3.jpg",
    category: "beauty-tools",
    description: "Premium brush set for flawless makeup application.",
    sizes: ["One Size"]
  },
  {
    id: 70,
    name: "Bath Bomb Box",
    brand: "LUSH",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.6,
    reviews: 133,
    image: "chudi4.jpg",
    category: "beauty-bath",
    description: "Relaxing bath bomb set for soothing spa-like baths.",
    sizes: ["One Size"]
  },
  {
    id: 71,
    name: "Hair Repair Oil",
    brand: "Matrix",
    price: 1599,
    originalPrice: 3199,
    discount: 50,
    rating: 4.4,
    reviews: 186,
    image: "cube.jpg",
    category: "beauty-haircare",
    description: "Nourishing hair oil for shine and strength.",
    sizes: ["One Size"]
  },
  {
    id: 72,
    name: "Lipstick Palette",
    brand: "MAC",
    price: 2199,
    originalPrice: 4399,
    discount: 50,
    rating: 4.7,
    reviews: 252,
    image: "drun1.jpg",
    category: "beauty-makeup",
    description: "Vibrant lipstick palette for every mood.",
    sizes: ["One Size"]
  },
  {
    id: 73,
    name: "Kids Denim Jacket",
    brand: "US POLO",
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.5,
    reviews: 190,
    image: "drun2.jpg",
    category: "kids-clothing",
    description: "Durable denim jacket for cool kids on chilly days.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 74,
    name: "Kids Cotton Tee",
    brand: "GAP",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.3,
    reviews: 145,
    image: "drun3.jpg",
    category: "kids-clothing",
    description: "Soft cotton tee for everyday comfort.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 75,
    name: "Kids Running Shoes",
    brand: "PUMA",
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    rating: 4.6,
    reviews: 205,
    image: "drun4.jpg",
    category: "kids-footwear",
    description: "Lightweight running shoes built for active kids.",
    sizes: ["10", "11", "12", "13"]
  },
  {
    id: 76,
    name: "Kids Casual Sandals",
    brand: "CROCS",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.2,
    reviews: 132,
    image: "el1.jpg",
    category: "kids-footwear",
    description: "Easy-wear sandals for summer fun.",
    sizes: ["10", "11", "12", "13"]
  },
  {
    id: 77,
    name: "Kids School Sneakers",
    brand: "NIKE",
    price: 1399,
    originalPrice: 2799,
    discount: 50,
    rating: 4.5,
    reviews: 170,
    image: "el2.jpg",
    category: "kids-footwear",
    description: "Durable school sneakers designed for comfort.",
    sizes: ["10", "11", "12", "13"]
  },
  {
    id: 78,
    name: "Kids Sun Hat",
    brand: "F&F",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.3,
    reviews: 98,
    image: "el3.jpg",
    category: "kids-accessories",
    description: "Cute and protective sun hat for outdoor play.",
    sizes: ["One Size"]
  },
  {
    id: 79,
    name: "Kids Wristwatch",
    brand: "TIMEX",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.4,
    reviews: 88,
    image: "el4.jpg",
    category: "kids-accessories",
    description: "Fun digital watch for everyday wear.",
    sizes: ["One Size"]
  },
  {
    id: 80,
    name: "Kids Sunglasses",
    brand: "SUNGLAM",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.5,
    reviews: 110,
    image: "electrical.jpg",
    category: "kids-accessories",
    description: "Stylish sunglasses made for little explorers.",
    sizes: ["One Size"]
  },
  {
    id: 81,
    name: "Kids Pajama Set",
    brand: "CARTER'S",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.6,
    reviews: 130,
    image: "esito1.jpg",
    category: "kids-outfits",
    description: "Soft pajama set for a cozy bedtime.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 82,
    name: "Kids School Uniform",
    brand: "LITTLECHAMPS",
    price: 1099,
    originalPrice: 2199,
    discount: 50,
    rating: 4.4,
    reviews: 145,
    image: "esito2.jpg",
    category: "kids-outfits",
    description: "Comfortable school uniform for everyday wear.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 83,
    name: "Kids Swim Set",
    brand: "ARENA",
    price: 1199,
    originalPrice: 2399,
    discount: 50,
    rating: 4.3,
    reviews: 95,
    image: "esito3.jpg",
    category: "kids-outfits",
    description: "Vibrant swim set perfect for pool days.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 84,
    name: "Kids Training Shorts",
    brand: "ADIDAS",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.5,
    reviews: 120,
    image: "esito4.jpg",
    category: "kids-sports",
    description: "Breathable training shorts for active kids.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 85,
    name: "Kids Baseball Cap",
    brand: "PUMA",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.2,
    reviews: 102,
    image: "fan1.jpg",
    category: "kids-sports",
    description: "Sporty cap ideal for outdoor games.",
    sizes: ["One Size"]
  },
  {
    id: 86,
    name: "Kids Sports Jersey",
    brand: "NIKE",
    price: 1099,
    originalPrice: 2199,
    discount: 50,
    rating: 4.4,
    reviews: 110,
    image: "fan2.jpg",
    category: "kids-sports",
    description: "Team-style jersey for kids who love sports.",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"]
  },
  {
    id: 87,
    name: "Kids Puzzle Game",
    brand: "LEGO",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.7,
    reviews: 98,
    image: "fan3.jpg",
    category: "kids-toys",
    description: "Fun puzzle game for building creativity.",
    sizes: ["One Size"]
  },
  {
    id: 88,
    name: "Kids Building Blocks",
    brand: "MEGA BLOKS",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.6,
    reviews: 105,
    image: "fan4.jpg",
    category: "kids-toys",
    description: "Colorful blocks for imaginative play.",
    sizes: ["One Size"]
  },
  {
    id: 89,
    name: "Kids Plush Toy",
    brand: "TY",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.5,
    reviews: 89,
    image: "formal1.jpg",
    category: "kids-toys",
    description: "Soft plush toy for bedtime cuddles.",
    sizes: ["One Size"]
  },
  {
    id: 90,
    name: "Eyeshadow Palette",
    brand: "NYX",
    price: 1599,
    originalPrice: 3199,
    discount: 50,
    rating: 4.5,
    reviews: 210,
    image: "formal2.jpg",
    category: "beauty-makeup",
    description: "Multi-shade palette for day and night looks.",
    sizes: ["One Size"]
  },
  {
    id: 91,
    name: "Liquid Lipstick",
    brand: "MAYBELLINE",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.4,
    reviews: 190,
    image: "formal3.jpg",
    category: "beauty-makeup",
    description: "Long-wear liquid lipstick with vibrant color.",
    sizes: ["One Size"]
  },
  {
    id: 92,
    name: "Moisturizing Cream",
    brand: "NIVEA",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.6,
    reviews: 220,
    image: "formal4.jpg",
    category: "beauty-skincare",
    description: "Daily moisturiser for smooth, hydrated skin.",
    sizes: ["One Size"]
  },
  {
    id: 93,
    name: "Charcoal Face Wash",
    brand: "BIOTIQUE",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.3,
    reviews: 150,
    image: "frock.jpg",
    category: "beauty-skincare",
    description: "Purifying face wash for refreshed skin.",
    sizes: ["One Size"]
  },
  {
    id: 94,
    name: "Sheet Mask Pack",
    brand: "TONYMOLY",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.5,
    reviews: 138,
    image: "furniture.jpg",
    category: "beauty-skincare",
    description: "Hydrating sheet masks for glowing skin.",
    sizes: ["One Size"]
  },
  {
    id: 95,
    name: "Eau de Parfum",
    brand: "CHANEL",
    price: 4999,
    originalPrice: 9999,
    discount: 50,
    rating: 4.8,
    reviews: 175,
    image: "girl1.jpg",
    category: "beauty-fragrance",
    description: "Sophisticated fragrance for day and evening.",
    sizes: ["One Size"]
  },
  {
    id: 96,
    name: "Body Mist",
    brand: "VICTORIA'S SECRET",
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    rating: 4.6,
    reviews: 160,
    image: "girl2.jpg",
    category: "beauty-fragrance",
    description: "Fresh body mist for everyday fragrance.",
    sizes: ["One Size"]
  },
  {
    id: 97,
    name: "Aromatic Roller",
    brand: "THE BODY SHOP",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.3,
    reviews: 130,
    image: "half1.jpg",
    category: "beauty-fragrance",
    description: "Portable roller for a quick scent refresh.",
    sizes: ["One Size"]
  },
  {
    id: 98,
    name: "Makeup Sponge Set",
    brand: "REAL TECHNIQUES",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.4,
    reviews: 145,
    image: "half2.jpg",
    category: "beauty-tools",
    description: "Soft sponges for flawless foundation application.",
    sizes: ["One Size"]
  },
  {
    id: 99,
    name: "Hair Straightener",
    brand: "CONAIR",
    price: 2799,
    originalPrice: 5599,
    discount: 50,
    rating: 4.5,
    reviews: 170,
    image: "half3.jpg",
    category: "beauty-tools",
    description: "Fast-heating straightener for sleek styling.",
    sizes: ["One Size"]
  },
  {
    id: 100,
    name: "Facial Cleansing Brush",
    brand: "FOREO",
    price: 3499,
    originalPrice: 6999,
    discount: 50,
    rating: 4.6,
    reviews: 184,
    image: "half4.jpg",
    category: "beauty-tools",
    description: "Gentle brush for deep cleansing and glow.",
    sizes: ["One Size"]
  },
  {
    id: 101,
    name: "Shower Gel Set",
    brand: "THE BODY SHOP",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.5,
    reviews: 142,
    image: "iron1.jpg",
    category: "beauty-bath",
    description: "Refreshing shower gels for daily use.",
    sizes: ["One Size"]
  },
  {
    id: 102,
    name: "Luxury Soap Bars",
    brand: "LUSH",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.4,
    reviews: 118,
    image: "iron2.jpg",
    category: "beauty-bath",
    description: "Aromatic soap bars for pampering showers.",
    sizes: ["One Size"]
  },
  {
    id: 103,
    name: "Body Lotion",
    brand: "NEUTROGENA",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.3,
    reviews: 135,
    image: "iron3.jpg",
    category: "beauty-bath",
    description: "Nourishing lotion for silky smooth skin.",
    sizes: ["One Size"]
  },
  {
    id: 104,
    name: "Nourishing Shampoo",
    brand: "HERBAL ESSENCES",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.6,
    reviews: 160,
    image: "iron4.jpg",
    category: "beauty-haircare",
    description: "Hydrating shampoo for soft, shiny hair.",
    sizes: ["One Size"]
  },
  {
    id: 105,
    name: "Conditioner Set",
    brand: "SUNDARPAHARI",
    price: 1199,
    originalPrice: 2399,
    discount: 50,
    rating: 4.5,
    reviews: 142,
    image: "kitt.jpg",
    category: "beauty-haircare",
    description: "Smoothing conditioner set for manageable hair.",
    sizes: ["One Size"]
  },
  {
    id: 106,
    name: "Hair Mask Treatment",
    brand: "L'OREAL",
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    rating: 4.7,
    reviews: 176,
    image: "ko1.jpg",
    category: "beauty-haircare",
    description: "Deep repair mask for healthier hair.",
    sizes: ["One Size"]
  },
  {
    id: 11,
    name: "Printed Kurti",
    brand: "GLOBAL DESI",
    price: 1599,
    originalPrice: 3199,
    discount: 50,
    rating: 4.6,
    reviews: 389,
    image: "ko2.jpg",
    category: "women-formals",
    description: "Beautiful printed kurti perfect for festivals and casual wear.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"]
  },
  {
    id: 12,
    name: "Running Shoes",
    brand: "PUMA",
    price: 3999,
    originalPrice: 7999,
    discount: 50,
    rating: 4.5,
    reviews: 678,
    image: "ko3.jpg",
    category: "shoes",
    description: "High-performance running shoes with advanced cushioning technology.",
    sizes: ["6", "7", "8", "9", "10", "11", "12"]
  },
  {
    id: 13,
    name: "Handbag Tote",
    brand: "FOSSIL",
    price: 3499,
    originalPrice: 6999,
    discount: 50,
    rating: 4.7,
    reviews: 445,
    image: "ko4.jpg",
    category: "women-accessories",
    description: "Stylish tote handbag perfect for daily use. Premium quality material.",
    sizes: ["One Size"]
  },
  {
    id: 14,
    name: "Graphic T-Shirt",
    brand: "UNIQLO",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.4,
    reviews: 523,
    image: "korean1.jpg",
    category: "tshirts",
    description: "Cool graphic t-shirt with unique designs. Made from soft cotton.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"]
  },
  {
    id: 15,
    name: "Saree with Blouse",
    brand: "BHAMA KADAM",
    price: 2899,
    originalPrice: 5799,
    discount: 50,
    rating: 4.6,
    reviews: 312,
    image: "korean2.jpg",
    category: "women-formals",
    description: "Traditional saree with matching blouse. Perfect for festivals and celebrations.",
    sizes: ["Free Size"]
  },
  {
    id: 16,
    name: "Cotton Shorts",
    brand: "DECATHLON",
    price: 599,
    originalPrice: 1199,
    discount: 50,
    rating: 4.3,
    reviews: 234,
    image: "korean3.jpg",
    category: "formals",
    description: "Comfortable cotton shorts perfect for summer. Lightweight and breathable.",
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: 17,
    name: "Formal Shirt",
    brand: "VAN HEUSEN",
    price: 1899,
    originalPrice: 3799,
    discount: 50,
    rating: 4.5,
    reviews: 200,
    image: "korean4.jpg",
    category: "shirts",
    description: "Classic formal shirt for office wear.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 18,
    name: "Casual Shirt",
    brand: "ALLEN SOLLY",
    price: 1599,
    originalPrice: 3199,
    discount: 50,
    rating: 4.3,
    reviews: 150,
    image: "laptop.jpg",
    category: "shirts",
    description: "Comfortable casual shirt.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 19,
    name: "Denim Shirt",
    brand: "LEE",
    price: 2199,
    originalPrice: 4399,
    discount: 50,
    rating: 4.6,
    reviews: 180,
    image: "laptop1.jpg",
    category: "shirts",
    description: "Stylish denim shirt.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 20,
    name: "V Neck T-Shirt",
    brand: "LEVIS",
    price: 1099,
    originalPrice: 2199,
    discount: 50,
    rating: 4.4,
    reviews: 120,
    image: "laptop2.jpg",
    category: "tshirts",
    description: "V neck t-shirt.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 21,
    name: "Round Neck T-Shirt",
    brand: "ADIDAS",
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    rating: 4.5,
    reviews: 140,
    image: "laptop3.jpg",
    category: "tshirts",
    description: "Round neck t-shirt.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 22,
    name: "Slim Fit Jeans",
    brand: "PEPE JEANS",
    price: 2799,
    originalPrice: 5599,
    discount: 50,
    rating: 4.7,
    reviews: 250,
    image: "laptop4.jpg",
    category: "jeans",
    description: "Slim fit jeans.",
    sizes: ["28", "30", "32", "34"]
  },
  {
    id: 23,
    name: "Straight Fit Jeans",
    brand: "LEE COOPER",
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.5,
    reviews: 200,
    image: "leh1.jpg",
    category: "jeans",
    description: "Straight fit jeans.",
    sizes: ["28", "30", "32", "34"]
  },
  {
    id: 24,
    name: "Skinny Jeans",
    brand: "SPYKAR",
    price: 2299,
    originalPrice: 4599,
    discount: 50,
    rating: 4.4,
    reviews: 180,
    image: "leh2.jpg",
    category: "jeans",
    description: "Skinny fit jeans.",
    sizes: ["28", "30", "32", "34"]
  },
  {
    id: 25,
    name: "Formal Trousers",
    brand: "RAYMOND",
    price: 2999,
    originalPrice: 5999,
    discount: 50,
    rating: 4.6,
    reviews: 160,
    image: "leh3.jpg",
    category: "formals",
    description: "Formal trousers.",
    sizes: ["28", "30", "32", "34"]
  },
  {
    id: 26,
    name: "Blazer",
    brand: "BLACKBERRY'S",
    price: 4999,
    originalPrice: 9999,
    discount: 50,
    rating: 4.8,
    reviews: 100,
    image: "leh4.jpg",
    category: "formals",
    description: "Formal blazer.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 27,
    name: "Cotton Hoodie",
    brand: "NIKE",
    price: 3499,
    originalPrice: 6999,
    discount: 50,
    rating: 4.7,
    reviews: 300,
    image: "lehanga.jpg",
    category: "hoodies",
    description: "Cotton hoodie.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 28,
    name: "Zip Hoodie",
    brand: "PUMA",
    price: 2999,
    originalPrice: 5999,
    discount: 50,
    rating: 4.5,
    reviews: 250,
    image: "pine1.jpg",
    category: "hoodies",
    description: "Zip hoodie.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 29,
    name: "Graphic Hoodie",
    brand: "ADIDAS",
    price: 3799,
    originalPrice: 7599,
    discount: 50,
    rating: 4.6,
    reviews: 220,
    image: "pine2.jpg",
    category: "hoodies",
    description: "Graphic hoodie.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 30,
    name: "Pullover Hoodie",
    brand: "REEBOK",
    price: 3199,
    originalPrice: 6399,
    discount: 50,
    rating: 4.4,
    reviews: 180,
    image: "pine3.jpg",
    category: "hoodies",
    description: "Pullover hoodie.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 31,
    name: "Loafers",
    brand: "WOODLAND",
    price: 3999,
    originalPrice: 7999,
    discount: 50,
    rating: 4.5,
    reviews: 150,
    image: "pine4.jpg",
    category: "shoes",
    description: "Formal loafers.",
    sizes: ["6", "7", "8", "9", "10"]
  },
  {
    id: 32,
    name: "Boots",
    brand: "RED TAPE",
    price: 4499,
    originalPrice: 8999,
    discount: 50,
    rating: 4.6,
    reviews: 200,
    image: "saree1.jpg",
    category: "shoes",
    description: "Stylish boots.",
    sizes: ["6", "7", "8", "9", "10"]
  },
  {
    id: 33,
    name: "Silk Shirt",
    brand: "ZARA",
    price: 2599,
    originalPrice: 4999,
    discount: 48,
    rating: 4.5,
    reviews: 220,
    image: "saree2.jpg",
    category: "women-shirts",
    description: "Lightweight silk shirt designed for women.",
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: 34,
    name: "Graphic Tee",
    brand: "H&M",
    price: 1299,
    originalPrice: 2499,
    discount: 48,
    rating: 4.4,
    reviews: 175,
    image: "saree3.jpg",
    category: "women-tshirts",
    description: "Comfortable graphic t-shirt for women.",
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: 35,
    name: "Skinny Jeans",
    brand: "LEVI'S",
    price: 2899,
    originalPrice: 5799,
    discount: 50,
    rating: 4.4,
    reviews: 190,
    image: "saree4.jpg",
    category: "women-jeans",
    description: "Slim-fit skinny jeans for women.",
    sizes: ["26", "28", "30", "32"]
  },
  {
    id: 36,
    name: "Heeled Boots",
    brand: "CLARKS",
    price: 3999,
    originalPrice: 7999,
    discount: 50,
    rating: 4.6,
    reviews: 210,
    image: "shoe1.jpg",
    category: "women-shoes",
    description: "Elegant heeled boots for women.",
    sizes: ["5", "6", "7", "8"]
  },
  {
    id: 37,
    name: "Silk Embroidered Saree",
    brand: "SAREE HOUSE",
    price: 5299,
    originalPrice: 10599,
    discount: 50,
    rating: 4.7,
    reviews: 180,
    image: "shoe2.jpg",
    category: "women-traditional-wear",
    description: "Rich silk saree with embroidered motifs for festive occasions.",
    sizes: ["Free Size"]
  },
  {
    id: 38,
    name: "Banarasi Lehenga Set",
    brand: "ETHNIC WEAR",
    price: 6999,
    originalPrice: 13999,
    discount: 50,
    rating: 4.8,
    reviews: 130,
    image: "shoe3.jpg",
    category: "women-traditional-wear",
    description: "Traditional Banarasi lehenga set with rich zari detailing.",
    sizes: ["S", "M", "L"]
  },
  {
    id: 39,
    name: "Anarkali Suit",
    brand: "MELANGE",
    price: 3999,
    originalPrice: 7999,
    discount: 50,
    rating: 4.6,
    reviews: 210,
    image: "shoe4.jpg",
    category: "women-traditional-wear",
    description: "Flowing Anarkali suit with golden embroidery.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 40,
    name: "Festive Kurta Set",
    brand: "BIBA",
    price: 2899,
    originalPrice: 5799,
    discount: 50,
    rating: 4.4,
    reviews: 160,
    image: "shoes.jpg",
    category: "women-traditional-wear",
    description: "Elegant kurta set with matching palazzos for traditional celebrations.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 41,
    name: "Denim Jacket Dress",
    brand: "FOREVER 21",
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.5,
    reviews: 145,
    image: "shop.jpg",
    category: "women-western",
    description: "Casual denim jacket dress for a chic western look.",
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: 42,
    name: "Sleeveless Jumpsuit",
    brand: "ZARA",
    price: 3299,
    originalPrice: 6599,
    discount: 50,
    rating: 4.6,
    reviews: 120,
    image: "stars.jpg",
    category: "women-western",
    description: "Stylish sleeveless jumpsuit for evening outings.",
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: 43,
    name: "Flared Top",
    brand: "H&M",
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.4,
    reviews: 155,
    image: "teddy1.jpg",
    category: "women-western",
    description: "Chic flared top for casual western styling.",
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: 44,
    name: "Tailored Trousers",
    brand: "MANGO",
    price: 2699,
    originalPrice: 5399,
    discount: 50,
    rating: 4.7,
    reviews: 170,
    image: "teddy2.jpg",
    category: "women-western",
    description: "Smart tailored trousers for everyday western wear.",
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: 45,
    name: "Chiffon Salwar Set",
    brand: "BIBA",
    price: 3299,
    originalPrice: 6599,
    discount: 50,
    rating: 4.5,
    reviews: 210,
    image: "teddy3.jpg",
    category: "women-salwar",
    description: "Elegant chiffon salwar set with delicate embroidery.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 46,
    name: "Embroidered Salwar Suit",
    brand: "GLOBAL DESI",
    price: 2799,
    originalPrice: 5599,
    discount: 50,
    rating: 4.6,
    reviews: 180,
    image: "teddy4.jpg",
    category: "women-salwar",
    description: "Traditional salwar suit with intricate embroidery.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 47,
    name: "Printed Salwar Kameez",
    brand: "W",
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.4,
    reviews: 165,
    image: "toy.jpg",
    category: "women-salwar",
    description: "Comfortable printed salwar kameez for daily wear.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 48,
    name: "Designer Salwar Set",
    brand: "AVON",
    price: 3499,
    originalPrice: 6999,
    discount: 50,
    rating: 4.7,
    reviews: 190,
    image: "train1.jpg",
    category: "women-salwar",
    description: "Designer salwar suit with modern print and fit.",
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 49,
    name: "Floral Maxi Dress",
    brand: "FOREVER 21",
    price: 2199,
    originalPrice: 4399,
    discount: 50,
    rating: 4.6,
    reviews: 175,
    image: "train2.jpg",
    category: "women-floral",
    description: "Soft floral maxi dress ideal for spring outings.",
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: 50,
    name: "Floral Co-ord Set",
    brand: "H&M",
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    rating: 4.5,
    reviews: 160,
    image: "train3.jpg",
    category: "women-floral",
    description: "Floral top and skirt co-ord set for a fresh look.",
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: 51,
    name: "Floral Wrap Top",
    brand: "ZARA",
    price: 1599,
    originalPrice: 3199,
    discount: 50,
    rating: 4.4,
    reviews: 145,
    image: "train4.jpg",
    category: "women-floral",
    description: "Wrap top with delicate floral print.",
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: 52,
    name: "Floral Midi Skirt",
    brand: "H&M",
    price: 1399,
    originalPrice: 2799,
    discount: 50,
    rating: 4.3,
    reviews: 150,
    image: "watergun1.jpg",
    category: "women-floral",
    description: "Lightweight midi skirt in bright floral print.",
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: 53,
    name: "Jeans with Crop Top",
    brand: "LEVIS",
    price: 2599,
    originalPrice: 5199,
    discount: 50,
    rating: 4.6,
    reviews: 170,
    image: "watergun2.jpg",
    category: "women-jeans-top",
    description: "High-waist jeans paired with a fitted crop top.",
    sizes: ["26", "28", "30", "32"]
  },
  {
    id: 54,
    name: "Denim Top and Jeans",
    brand: "MANGO",
    price: 2799,
    originalPrice: 5599,
    discount: 50,
    rating: 4.5,
    reviews: 155,
    image: "watergun3.jpg",
    category: "women-jeans-top",
    description: "Denim top paired with skinny jeans for a coordinated look.",
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: 55,
    name: "Ripped Jeans with Tank",
    brand: "H&M",
    price: 2299,
    originalPrice: 4599,
    discount: 50,
    rating: 4.4,
    reviews: 140,
    image: "watergun4.jpg",
    category: "women-jeans-top",
    description: "Ripped jeans styled with a casual tank top.",
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: 56,
    name: "Printed Jeans Top Set",
    brand: "FOREVER 21",
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.5,
    reviews: 160,
    image: "arito1.jpg",
    category: "women-jeans-top",
    description: "Printed top paired with matching jeans.",
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: 57,
    name: "Sequin Party Dress",
    brand: "ZARA",
    price: 4199,
    originalPrice: 8399,
    discount: 50,
    rating: 4.7,
    reviews: 195,
    image: "arito2.jpg",
    category: "women-party",
    description: "Shimmering sequin dress for evening parties.",
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: 58,
    name: "Satin Party Gown",
    brand: "FOREVER 21",
    price: 4599,
    originalPrice: 9199,
    discount: 50,
    rating: 4.6,
    reviews: 180,
    image: "arito3.jpg",
    category: "women-party",
    description: "Elegant satin gown ideal for special occasions.",
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: 59,
    name: "Glitter Skirt Set",
    brand: "H&M",
    price: 3399,
    originalPrice: 6799,
    discount: 50,
    rating: 4.5,
    reviews: 165,
    image: "arito4.jpg",
    category: "women-party",
    description: "Glitter skirt and top set for a glam night out.",
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: 60,
    name: "Evening Jumpsuit",
    brand: "ZARA",
    price: 3799,
    originalPrice: 7599,
    discount: 50,
    rating: 4.6,
    reviews: 170,
    image: "baby1.jpg",
    category: "women-party",
    description: "Sophisticated evening jumpsuit for a refined look.",
    sizes: ["XS", "S", "M", "L"]
  }
];


const seedProducts = async () => {
  try {
    await sequelize.authenticate();
    console.log("DB connected");

    await sequelize.sync({ alter: true });

    await Product.destroy({ where: {} });

    await Product.bulkCreate(products);

    console.log("✅ All products inserted successfully");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
};

seedProducts();
